[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
dotenvy = "0.15"
tokio = { version = "1.33", features = ["full"] }
shared = { path = "../shared" }
